plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
}

android {
    namespace = "me.androidloader"
    compileSdk = 35

    defaultConfig {
        applicationId = "me.androidloader"
        minSdk = 26
        targetSdk = 35
        versionCode = 1
        versionName = "0.1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        // Debug keystore is auto-generated by AGP, so no explicit debug config is needed.
        // A release keystore is supplied through gradle properties on CI (see
        // .github/workflows/android.yml). Without them, release falls back to unsigned.
        val keystorePath = providers.gradleProperty("ANDROIDLOADER_KEYSTORE").orNull
        if (keystorePath != null) {
            create("release") {
                storeFile = file(keystorePath)
                storePassword = providers.gradleProperty("ANDROIDLOADER_KEYSTORE_PASSWORD").get()
                keyAlias = providers.gradleProperty("ANDROIDLOADER_KEY_ALIAS").get()
                keyPassword = providers.gradleProperty("ANDROIDLOADER_KEY_PASSWORD").get()
            }
        }
    }

    buildTypes {
        debug {
            applicationIdSuffix = ".debug"
            versionNameSuffix = "-debug"
        }
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
            if (providers.gradleProperty("ANDROIDLOADER_KEYSTORE").isPresent) {
                signingConfig = signingConfigs.getByName("release")
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
        isCoreLibraryDesugaringEnabled = true
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
    }

    testOptions {
        unitTests {
            isIncludeAndroidResources = true
            // Lets tests that touch framework stubs call them instead of throwing.
            // Tests needing real Intent behaviour use Robolectric explicitly.
            isReturnDefaultValues = true
        }
    }

    packaging {
        resources {
            // Each BouncyCastle artifact ships an OSGi manifest under its own
            // multi-release directory, and those collide during
            // mergeDebugJavaResource. They are packaging metadata with no runtime
            // effect. Only the manifests are excluded: the classes alongside them
            // under META-INF/versions are real and must be kept.
            excludes += "META-INF/versions/*/OSGI-INF/MANIFEST.MF"
            excludes += "META-INF/OSGI-INF/MANIFEST.MF"
            excludes += "META-INF/DEPENDENCIES"
            excludes += "META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

dependencies {
    coreLibraryDesugaring(libs.desugar.jdk.libs)

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.material.icons)
    implementation(libs.androidx.navigation.compose)
    implementation(libs.androidx.datastore.preferences)
    implementation(libs.kotlinx.coroutines.android)

    // Apple's provisioning/codesigning layer needs a full JCE with CMS/PKCS#12
    // support. The Android platform provider omits those, so BouncyCastle is
    // bundled. bcpkix supplies the X.509 builder APIs used to mint the pairing
    // host certificate; bcprov and bcutil are its crypto and ASN.1 helpers.
    implementation(libs.bcpkix)
    implementation(libs.bcpkix.jdk18on)
    implementation(libs.bcutil)

    debugImplementation(libs.androidx.compose.ui.tooling)

    testImplementation(libs.junit)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.compose.ui.test.junit4)
    // Supplies the ComponentActivity the Compose test rule needs.
    debugImplementation(libs.compose.ui.test.manifest)
}
